services:
  mediuxarr:
    image: ghcr.io/captsonic/mediuxarr:${MEDIUXARR_VERSION:-latest}
    container_name: mediuxarr
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MEDIUXARR_SECRET_KEY: ${MEDIUXARR_SECRET_KEY:-}
      MEDIUXARR_MEDIUX_API_TOKEN: ${MEDIUXARR_MEDIUX_API_TOKEN:-}
      TZ: ${TZ:-Europe/Berlin}
    volumes:
      - ./config:/config
      - ${KOMETA_ASSET_PATH:-./kometa-assets}:/kometa-assets
